### ISSUE TITLE
undefined method `cells' for #<Array:0x007f8ba99466f0>

### ISSUE THREAD

**Issue by ethicalhack3r** [tj/terminal-table#59] opened 2015-07-02 08:41 UTC
Hi,

We're getting the ```undefined method `cells' for #<Array:0x007f8ba99466f0>``` error in WPScan with terminal-table 1.5.2.

Full stack trace:
```
[!] undefined method `cells' for #<Array:0x007f902bd9c0e8>
[!] Trace:
[!] /Users/ryan/Tools/wpscan/lib/common/hacks.rb:69:in `render'
/Users/ryan/Tools/wpscan/lib/common/collections/wp_users/output.rb:25:in `output'
./wpscan.rb:364:in `main'
./wpscan.rb:443:in `<main>'
```

To reproduce:
```/wpscan.rb -u www.somewordpresssite.com -w password-list.txt```

Being tracked here by our users - https://github.com/wpscanteam/wpscan/issues/841

**Comment by ethicalhack3r** [comment] 2015-07-02 08:43
Line 69 of ```/Users/ryan/Tools/wpscan/lib/common/hacks.rb``` is ```unless @headings.cells.empty?```

**Comment by erwanlr** [comment] 2015-07-02 14:51
This is not a bug in the the gem, but as the code has been updated some days ago:

```unless @headings.cells.empty?```

to

```
@headings.each do |row|
    unless row.cells.empty?
```

The monkey patch should also have been update on our side (I should have noticed that when rebasing the #32)

I think we will keep the v1.4.5 until the #32 is merged :)

**Comment by nateberkopec** [comment] 2015-07-03 19:30
Yeah, the problem is in your monkey patch, not our code. #32 is merged, hopefully you can remove your monkey patch completely.

**Closed by nateberkopec** 2015-07-03 19:30 UTC
Labels: bug
